# ! This YML Action is named as ITW Site Publisher
# - It empowers worker-branch capabilities of automatically publishing the changes to the `master` branch.

# ! This action DOES NOT handle manual / explicit pushing in Master Branch.
# - Why?
# -   Because for every commit, the changes are being built by the Github Pages automatically.

## Add ESLINTER here soon.
## Add Prettier here soon.
name: Gatsby-Powered ITW Publisher CI
on:
  push: worker-branch
  pull_requests: worker-branch

jobs:
  build:
    runs-on:ubuntu-latest

# ! { incomplete }